### ISSUE TITLE
Unknown task definition arn

### ISSUE THREAD

**Issue by jaedung** [donaldpiret/ecs-deploy#4]
I was trying to use the `fargate task definition` to run a `one-off task` in the `EC2 linux cluster` not Fargate however I've got the error `Unknown task definition arn`.
I've used the full ARN of the task definition as `target`.

I followed the instruction below.
https://github.com/donaldpiret/ecs-deploy#running-a-task

**Comment by donaldpiret** [comment]
Sorry for getting back to this so late. Are you by any chance able to paste the relevant part of your github actions workflow?

**Comment by donaldpiret** [comment]
Will mark this as closed given how much time has passed. If you're still experiencing this please feel free to re-open!

**Comment by jemisonf** [comment]
I ran into this as well and the issue is _probably_ that the service account is missing the necessary IAM permissions. I think this specific error comes from missing `ecs:ListTaskDefinitions`.

**Comment by donaldpiret** [comment]
@jemisonf thanks for the info! Have added a short section to the README which hopefully will help others out.
